#ifndef IMAGES_H__
#define IMAGES_H__

#include <stdint.h>
#include <stdbool.h>

#define BLACK	{0x00, 0x00, 0x00}
#define WHITE	{0xFF, 0xEB, 0xD4}
#define YELLO	{0xFF, 0xEB, 0x00}
#define BROWN	{0x2B, 0x17, 0x00}
#define ORANG	{0xFF, 0xA5, 0x00}
#define C_RED	{0xFF, 0x00, 0x00}
#define BEIGE	{0x79, 0x5C, 0x32}
#define DBLUE	{0x00, 0x00, 0x8B}


uint8_t emojiSunGlass16[16][16][3] =
{
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,BLACK,BLACK,WHITE,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,BLACK,YELLO,BROWN,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,BLACK,YELLO,BROWN,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,BLACK,YELLO,BROWN,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,BLACK,YELLO,BROWN,YELLO,YELLO,BLACK,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,BROWN,YELLO,BLACK,BLACK,WHITE,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE}
};

uint8_t emojiSunGlass32[32][32][3] =
{
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,WHITE,BLACK,WHITE,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,BLACK,WHITE,BLACK,WHITE,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLO,YELLO,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,YELLO,YELLO,YELLO,YELLO,YELLO,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE}
};

uint8_t imgSuperMario32[32][32][3] =
{
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,BROWN,BROWN,BROWN,BLACK,BLACK,WHITE,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE,BLACK,BEIGE,BEIGE,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,BLACK,BROWN,BROWN,BROWN,BROWN,BROWN,BLACK,BLACK,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BROWN,BLACK,BEIGE,BEIGE,BLACK,C_RED,C_RED,C_RED,BLACK,BLACK,BEIGE,BEIGE,BLACK,BLACK,BLACK,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,DBLUE,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,C_RED,C_RED,BLACK,BEIGE,BEIGE,BLACK,BLACK,BLACK,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,C_RED,BLACK,BLACK,BEIGE,BEIGE,BEIGE,BLACK,BEIGE,BEIGE,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,C_RED,BLACK,BEIGE,BEIGE,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,DBLUE,BLACK,BEIGE,BEIGE,BLACK,DBLUE,BLACK,BLACK,BEIGE,BEIGE,BLACK,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,C_RED,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,DBLUE,BLACK,BLACK,DBLUE,BLACK,BLACK,BLACK,BEIGE,BLACK,BLACK,BEIGE,BEIGE,BLACK,BLACK,BEIGE,BLACK,BLACK,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,DBLUE,DBLUE,DBLUE,BLACK,C_RED,C_RED,BLACK,BEIGE,BLACK,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,BLACK,C_RED,C_RED,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,DBLUE,DBLUE,DBLUE,DBLUE,BLACK,C_RED,C_RED,C_RED,BLACK,BEIGE,BLACK,BEIGE,BEIGE,BEIGE,BLACK,BLACK,BEIGE,BLACK,BLACK,C_RED,BLACK,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,DBLUE,DBLUE,BLACK,C_RED,C_RED,BLACK,BLACK,BLACK,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BROWN,BROWN,BROWN,BROWN,BLACK,DBLUE,BLACK,C_RED,BLACK,BLACK,C_RED,C_RED,BLACK,BLACK,BEIGE,BEIGE,BLACK,BLACK,BLACK,BLACK,BLACK,BEIGE,BEIGE,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BROWN,BROWN,BROWN,BROWN,BROWN,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,C_RED,C_RED,BLACK,BLACK,BLACK,C_RED,C_RED,BLACK,BLACK,BEIGE,BEIGE,BEIGE,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BROWN,BROWN,BROWN,BROWN,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,C_RED,C_RED,C_RED,C_RED,BLACK,BEIGE,BEIGE,BEIGE,BEIGE,BLACK,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE}
};



#undef BLACK
#undef WHITE
#undef YELLO
#undef BROWN
#undef ORANG
#undef C_RED

#endif
